#!/bin/bash
# 更新README.md中的所有链接路径

sed -i 's|\./SQL基础培训\.md|./01-SQL基础/SQL基础培训.md|g' README.md
sed -i 's|\./事务管理详解\.md|./15-体系总览/事务管理详解.md|g' README.md
sed -i 's|\./索引与查询优化\.md|./01-SQL基础/索引与查询优化.md|g' README.md
sed -i 's|\./查询计划与优化器\.md|./01-SQL基础/查询计划与优化器.md|g' README.md
sed -i 's|\./并发控制详解\.md|./15-体系总览/并发控制详解.md|g' README.md
sed -i 's|\./锁机制详解\.md|./15-体系总览/锁机制详解.md|g' README.md
sed -i 's|\./数据库设计最佳实践\.md|./14-设计/数据库设计最佳实践.md|g' README.md
sed -i 's|\./数据类型详解\.md|./03-数据类型/数据类型详解.md|g' README.md
sed -i 's|\./数据类型体系详解\.md|./03-数据类型/数据类型体系详解.md|g' README.md
sed -i 's|\./函数与存储过程\.md|./04-函数与编程/函数与存储过程.md|g' README.md
sed -i 's|\./SQL函数体系详解\.md|./01-SQL基础/SQL函数体系详解.md|g' README.md
sed -i 's|\./视图与物化视图\.md|./05-数据管理/视图与物化视图.md|g' README.md
sed -i 's|\./高级 SQL 特性\.md|./02-SQL高级特性/高级SQL特性.md|g' README.md
sed -i 's|\./高级SQL特性\.md|./02-SQL高级特性/高级SQL特性.md|g' README.md
sed -i 's|\./窗口函数详解\.md|./02-SQL高级特性/窗口函数详解.md|g' README.md
sed -i 's|\./CTE详解\.md|./02-SQL高级特性/CTE详解.md|g' README.md
sed -i 's|\./递归查询详解\.md|./02-SQL高级特性/递归查询详解.md|g' README.md
sed -i 's|\./LATERAL连接详解\.md|./02-SQL高级特性/LATERAL连接详解.md|g' README.md
sed -i 's|\./FILTER子句详解\.md|./02-SQL高级特性/FILTER子句详解.md|g' README.md
sed -i 's|\./CASE表达式详解\.md|./02-SQL高级特性/CASE表达式详解.md|g' README.md
sed -i 's|\./数组与JSONB高级应用\.md|./03-数据类型/数组与JSONB高级应用.md|g' README.md
sed -i 's|\./范围类型详解\.md|./03-数据类型/范围类型详解.md|g' README.md
sed -i 's|\./自定义类型详解\.md|./03-数据类型/自定义类型详解.md|g' README.md
sed -i 's|\./NULL值处理详解\.md|./03-数据类型/NULL值处理详解.md|g' README.md
sed -i 's|\./全文搜索详解\.md|./03-数据类型/全文搜索详解.md|g' README.md
sed -i 's|\./正则表达式详解\.md|./03-数据类型/正则表达式详解.md|g' README.md
sed -i 's|\./PL-pgSQL编程详解\.md|./04-函数与编程/PL-pgSQL编程详解.md|g' README.md
sed -i 's|\./触发器高级应用\.md|./04-函数与编程/触发器高级应用.md|g' README.md
sed -i 's|\./字符串函数详解\.md|./04-函数与编程/字符串函数详解.md|g' README.md
sed -i 's|\./日期时间函数详解\.md|./04-函数与编程/日期时间函数详解.md|g' README.md
sed -i 's|\./数学函数详解\.md|./04-函数与编程/数学函数详解.md|g' README.md
sed -i 's|\./聚合函数详解\.md|./04-函数与编程/聚合函数详解.md|g' README.md
sed -i 's|\./分区表管理\.md|./05-数据管理/分区表管理.md|g' README.md
sed -i 's|\./约束管理\.md|./05-数据管理/约束管理.md|g' README.md
sed -i 's|\./序列管理\.md|./05-数据管理/序列管理.md|g' README.md
sed -i 's|\./游标管理\.md|./05-数据管理/游标管理.md|g' README.md
sed -i 's|\./规则系统\.md|./05-数据管理/规则系统.md|g' README.md
sed -i 's|\./表空间与存储管理\.md|./06-存储管理/表空间与存储管理.md|g' README.md
sed -i 's|\./存储管理体系详解\.md|./06-存储管理/存储管理体系详解.md|g' README.md
sed -i 's|\./VACUUM与维护\.md|./06-存储管理/VACUUM与维护.md|g' README.md
sed -i 's|\./权限管理\.md|./07-安全/权限管理.md|g' README.md
sed -i 's|\./安全与加密\.md|./07-安全/安全与加密.md|g' README.md
sed -i 's|\./安全体系详解\.md|./07-安全/安全体系详解.md|g' README.md
sed -i 's|\./备份与恢复\.md|./08-备份恢复/备份与恢复.md|g' README.md
sed -i 's|\./备份恢复体系详解\.md|./08-备份恢复/备份恢复体系详解.md|g' README.md
sed -i 's|\./复制与高可用\.md|./09-高可用/复制与高可用.md|g' README.md
sed -i 's|\./高可用体系详解\.md|./09-高可用/高可用体系详解.md|g' README.md
sed -i 's|\./监控与诊断\.md|./10-监控诊断/监控与诊断.md|g' README.md
sed -i 's|\./监控诊断体系详解\.md|./10-监控诊断/监控诊断体系详解.md|g' README.md
sed -i 's|\./日志管理与分析\.md|./10-监控诊断/日志管理与分析.md|g' README.md
sed -i 's|\./性能调优深入\.md|./11-性能调优/性能调优深入.md|g' README.md
sed -i 's|\./性能调优体系详解\.md|./11-性能调优/性能调优体系详解.md|g' README.md
sed -i 's|\./性能测试与基准测试\.md|./11-性能调优/性能测试与基准测试.md|g' README.md
sed -i 's|\./扩展管理\.md|./12-扩展开发/扩展管理.md|g' README.md
sed -i 's|\./扩展开发指南\.md|./12-扩展开发/扩展开发指南.md|g' README.md
sed -i 's|\./扩展开发体系详解\.md|./12-扩展开发/扩展开发体系详解.md|g' README.md
sed -i 's|\./运维管理体系详解\.md|./13-运维管理/运维管理体系详解.md|g' README.md
sed -i 's|\./统计信息管理\.md|./13-运维管理/统计信息管理.md|g' README.md
sed -i 's|\./连接池管理\.md|./13-运维管理/连接池管理.md|g' README.md
sed -i 's|\./外部数据包装器\.md|./14-设计/外部数据包装器.md|g' README.md
sed -i 's|\./逻辑复制详解\.md|./09-高可用/逻辑复制详解.md|g' README.md
sed -i 's|\./PostgreSQL知识体系总览\.md|./15-体系总览/PostgreSQL知识体系总览.md|g' README.md
sed -i 's|\./事务与并发体系详解\.md|./15-体系总览/事务与并发体系详解.md|g' README.md
sed -i 's|\./查询优化体系详解\.md|./01-SQL基础/查询优化体系详解.md|g' README.md
sed -i 's|\./索引体系详解\.md|./01-SQL基础/索引体系详解.md|g' README.md

echo "链接路径更新完成！"
