version: "3.8"
services:
  coordinator:
    image: citusdata/citus:12.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    depends_on:
      - worker1
      - worker2
    command: ["bash", "-c", "postgres -c shared_preload_libraries=citus -c max_wal_senders=10 -c wal_level=logical"]
  worker1:
    image: citusdata/citus:12.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    command: ["bash", "-c", "postgres -c shared_preload_libraries=citus -c max_wal_senders=10 -c wal_level=logical"]
  worker2:
    image: citusdata/citus:12.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    command: ["bash", "-c", "postgres -c shared_preload_libraries=citus -c max_wal_senders=10 -c wal_level=logical"]
  manager:
    image: citusdata/citus:12.1
    depends_on:
      - coordinator
      - worker1
      - worker2
    entrypoint: ["bash", "-lc"]
    command: >
      "until pg_isready -h coordinator -p 5432; do sleep 1; done &&
       psql postgresql://postgres:postgres@coordinator:5432/postgres -v ON_ERROR_STOP=1 -c \"CREATE EXTENSION IF NOT EXISTS citus;\" &&
       psql postgresql://postgres:postgres@coordinator:5432/postgres -v ON_ERROR_STOP=1 -c \"SELECT * FROM master_add_node('worker1', 5432);\" &&
       psql postgresql://postgres:postgres@coordinator:5432/postgres -v ON_ERROR_STOP=1 -c \"SELECT * FROM master_add_node('worker2', 5432);\" &&
       echo 'Citus cluster ready'"

